dev_6/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
]

dev_6/dev_6/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from dev_6 import settings

urlpatterns = [
    path('', include('mainapp.urls', namespace='mainapp')),

    path('accounts/', include('authapp.urls', namespace='authapp')),

    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dev_6/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
]

dev_6/authapp/models.py
from django.db import models

dev_6/mainapp/models.py
from django.db import models


class Photo(models.Model):
    name = models.CharField(verbose_name='Название', max_length=64, blank=True)
    image = models.ImageField(verbose_name='Фотография', upload_to='img/')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'

dev_6/authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'form-control {name}'


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'form-control {name}'
            item.help_text = ''

dev_6/authapp/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from authapp.forms import LoginForm, RegisterForm


def login(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            auth.login(request, form.get_user())
            return HttpResponseRedirect(reverse('mainapp:index'))
    else:
        form = LoginForm()

    context = {
        'form': form,
        'page_title': 'авторизация',
    }
    return render(request, 'authapp/login.html', context)


@login_required
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('authapp:login'))


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('authapp:login'))
    else:
        form = RegisterForm()
    context = {
        'page_title': 'регистрация',
        'form': form,
    }
    return render(request, 'authapp/register.html', context)

dev_6/mainapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from mainapp.models import Photo
import random


@login_required()
def index(request):
    num_img = Photo.objects.all()
    random_img = random.choices(num_img)
    context = {
        'title': 'главная',
        'num_img': random_img,
    }
    return render(request, 'mainapp/index.html', context)

dev_6/authapp/templates/authapp/login.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <title>{{ page_title|default:"аутентификация"|capfirst }}</title>

    <style>
        html{
            padding: 0;
            margin: 0;
            width: 100%;
            height: 100%;
        }
        body{
            background-color: #333333!important;
            color: #fff;
            display: flex;
            align-items: center;
            padding-top: 15%;
            /*padding-bottom: 40px;*/
        }
        .form-signin {
          width: 100%;
          max-width: 330px;
          padding: 15px;
          margin: auto;
        }
        .avtoriz {
            text-align: center;
        }
        .zar {
            text-decoration: none;
            background-color: red;
            padding: 10px;
            margin-top: 50px;
            text-transform: uppercase;
            color: #fff;
            font-weight: bold;
        }
        .vxot {
            margin-bottom: 30px;
            background-color: #25ff58;
            padding: 10px;
            text-transform:uppercase;
            color: #000;
            font-weight: bold;
        }
    </style>
</head>
<body class="text-center">
<main class="form-signin">
    <form method="post">
        <h1 class="avtoriz">Авторизация</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <div class="row">
            <input type="submit" class="vxot"
                   value="Войти">
            <a href="{% url 'authapp:register' %}" class="zar">Зарегистрироваться</a>
        </div>

    </form>
</main>
</body>
</html>

dev_6/authapp/templates/authapp/register.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <title>{{ page_title|default:"аутентификация"|capfirst }}</title>
    <style>
    html{
            padding: 0;
            margin: 0;
            width: 100%;
            height: 100%;
        }
        body{
            background-color: #333333!important;
            color: #fff;
            display: flex;
            align-items: center;
            padding-top: 15%;
            /*padding-bottom: 40px;*/
        }
        .form-signin {
          width: 100%;
          max-width: 330px;
          padding: 15px;
          margin: auto;
        }
        .avtoriz {
            text-align: center;
        }
        .zar {
            text-decoration: none;
            background-color: #25ff58;
            padding: 10px;
            margin-top: 50px;
            /*border-radius: 20%;*/
            text-transform: uppercase;
            color: #000;
            font-weight: bold;
        }
        .vxot {
            margin-bottom: 30px;
            background-color: red;
            padding: 10px;
            text-transform: uppercase;
            text-decoration: none;
            color: #fff;
            font-weight: bold;
        }
    </style>
</head>
<body class="text-center">
<main class="form-signin">
    <form method="post">
        <h1 class="avtoriz">Регистрация</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <div class="row">
            <input type="submit" class="zar"
                       value="Зарегистрироваться">
            <a href="{% url 'authapp:login' %}" class="vxot">Войти</a>
        </div>
    </form>
</main>
</body>
</html>

dev_6/mainapp/templates/mainapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|default:"аутентификация"|capfirst }}</title>
    <style>
        body {
            background-color: #333333;
            color: #fff;
        }
        li {

            list-style-type: none;
            display: inline;
            margin-right: 5px;
            padding: 3px;
        }
        li a {
            text-decoration: none;
            text-transform:uppercase;
            font-size: 20px;
            font-weight: bold;
            color: #fff;
        }
        li a:hover {
            color: #03ff00;
            transition: .4s ease-out;
        }
        a.user {
            color: #fff;
            text-decoration: none;
        }
        a.user:hover {
            color: red;
            transition: .4s ease-out;
        }
    </style>
</head>
<body>
<nav class="menu">
    <div class="container">
            <ul class="">
                <li><a href="{% url 'mainapp:index' %}" class="nav-link px-2 text-secondary">Главная</a></li>
            </ul>
            <div class="text-end">
                {% if user.is_authenticated %}
                    <span class="user">{{ user.username }}</span>
                    <a href="{% url 'authapp:logout' %}" class="user">Выйти</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

<main class="container mt-3">
    {% for item in num_img %}
        <img style="width: 50%;" src="{{ item.image.url }}">
    {% endfor %}
</main>

</body>
</html>